#!/bin/bash

# Inspired by https://github.com/thiagommedeiros/dotfiles

GREEN='\033[0;32m'
RED="\033[0;31m"
NC="\033[0m"

function p_red() {
  printf "\n${RED}$1${NC}\n"
}

function p_green() {
  printf "\n${GREEN}$1${NC}\n"
}

function backup() {
  p_red "[BACKUP] Oh-my-zsh"
  cp ~/.zshrc zsh/
  p_green "[BACKUP] Oh-my-zsh: DONE\!"

  p_red "[BACKUP] Terminator"
  cp ~/.config/terminator/config terminator/config
  p_green "[BACKUP] Terminator: DONE\!"

  p_red "[BACKUP] Git"
  cp ~/.gitconfig git/
  p_green "[BACKUP] Git: DONE\!"

  p_red "[BACKUP] Sublime Text 3"
  cp ~/.config/sublime-text-3/Packages/User/Package\ Control.sublime-settings st3/Package\ Control.sublime-settings
  cp ~/.config/sublime-text-3/Packages/User/Base\ File.sublime-settings st3/Base\ File.sublime-settings
  cp ~/.config/sublime-text-3/Packages/User/Preferences.sublime-settings st3/Preferences.sublime-settings
  cp ~/.config/sublime-text-3/Packages/User/Emmet.sublime-settings st3/Emmet.sublime-settings
  p_green "[BACKUP] Sublime Text 3: DONE\!"
}

read -p "You are logged as ${USER}, do you wanna continue? [y/n] " cont
if [ "$cont" = "y" ]; then
  backup
fi
