#!/bin/bash

# Inspired by https://github.com/thiagommedeiros/dotfiles

GREEN='\033[0;32m'
RED="\033[0;31m"
NC="\033[0m"

function p_red() {
  printf "\n${RED}$1${NC}\n"
}

function p_green() {
  printf "\n${GREEN}$1${NC}\n"
}

function customize() {
  p_red "Customizing omz..."
  sed -i "s/USER/${USER}/" zsh/.zshrc
  cp zsh/.zshrc ~/
  cp zsh/materialshell-oceanic.zsh-theme ~/.oh-my-zsh/themes

  p_red "Customizing terminator..."
  mkdir ~/.config/terminator/
  cp terminator/config ~/.config/terminator/config

  p_red "Customizing git..."
  cp git/.gitconfig ~/

  p_red "Customizing sublime-text-3..."
  cp st3/Package\ Control.sublime-settings ~/.config/sublime-text-3/Packages/User/Package\ Control.sublime-settings
  cp st3/Base\ File.sublime-settings ~/.config/sublime-text-3/Packages/User/Base\ File.sublime-settings
  cp st3/Preferences.sublime-settings ~/.config/sublime-text-3/Packages/User/Preferences.sublime-settings
  cp st3/Emmet.sublime-settings ~/.config/sublime-text-3/Packages/User/Emmet.sublime-settings
  cd ~/.config/sublime-text-3/Installed\ Packages/
  wget https://packagecontrol.io/Package%20Control.sublime-package
  cd
}

customize

p_green "[CUSTOMIZE]: Done!"
