#!/bin/bash

# Inspired by https://github.com/thiagommedeiros/dotfiles

GREEN='\033[0;32m'
RED="\033[0;31m"
NC="\033[0m"

function p_red() {
  printf "\n${RED}$1${NC}\n"
}

function p_green() {
  printf "\n${GREEN}$1${NC}\n"
}

function customize() {
  p_red "Customizing omz..."
  TEST_CURRENT_SHELL=$(expr "$SHELL" : '.*/\(.*\)')
  if [ "$TEST_CURRENT_SHELL" != "zsh" ]; then
    if hash chsh >/dev/null 2>&1; then
      chsh -s $(grep /zsh$ /etc/shells | tail -1)
    fi
  fi
  sed -i "s/USER/${USER}/" zsh/.zshrc
  cp zsh/.zshrc ~/
  cp zsh/materialshell-oceanic.zsh-theme ~/.oh-my-zsh/themes

  p_red "Customizing terminator..."
  mkdir ~/.config/terminator/
  cp terminator/config ~/.config/terminator/config

  p_red "Customizing git..."
  cp git/.gitconfig ~/

  p_red "Customizing sublime-text-3..."
  cp st3/Package\ Control.sublime-settings ~/.config/sublime-text-3/Packages/User/Package\ Control.sublime-settings
  cp st3/Base\ File.sublime-settings ~/.config/sublime-text-3/Packages/User/Base\ File.sublime-settings
  cp st3/Preferences.sublime-settings ~/.config/sublime-text-3/Packages/User/Preferences.sublime-settings
  cp st3/Emmet.sublime-settings ~/.config/sublime-text-3/Packages/User/Emmet.sublime-settings
  cd ~/.config/sublime-text-3/Installed\ Packages/
  wget https://packagecontrol.io/Package%20Control.sublime-package
  cd

  p_red "Customizing desktop folder..."
  mv Área\ de\ Trabalho/ Desktop/
  sed -i "s/Área de Trabalho/Desktop/" ~/.config/user-dirs.dirs

  p_red "Customizing nginx..."
  sed -i "s/USER/${USER}/" nginx/NGINX
  mkdir ~/Desktop/NGINX/
  cp nginx/NGINX /etc/nginx/sites-enabled/NGINX
  sudo service nginx stop
  sudo service nginx start
}

if [ "$USER" = "root" ]; then
  read -p "You are logged as root, do you wanna continue? [y/n] " cont
  if [ "$cont" = "y" ]; then
    customize
    zsh
  else
    exit
  fi
else
  customize
fi

p_green "[CUSTOMIZE]: Done!"
