#!/bin/bash

# Inspired by https://github.com/thiagommedeiros/dotfiles

YELLOW="\033[1;33m"
GREEN='\033[1;32m'
NC="\033[0m"

function p_yellow() {
  printf "\n${YELLOW}$1${NC}\n"
}

function p_green() {
  printf "\n${GREEN}$1${NC}\n"
}

function i_fonts() {
  mkdir /tmp/$1
  wget $2 -O "`echo /tmp/$1/$1`.zip"
  unzip -o -j /tmp/$1/$1.zip -d /tmp/$1/
  sudo mkdir /usr/share/fonts/truetype/$1
  sudo cp -rf /tmp/$1/. /usr/share/fonts/truetype/$1/.
  fc-cache -f -v
}

function install() {
  p_yellow "[UPDATE] APT-GET"
  sudo apt-get -y update
  p_green "[UPDATE] APT-GET: DONE\!"

  read -p "Do you wanna continue? [y/n] " cont
  if [ "$cont" = "n" ]; then
    return 1;
  fi

  p_yellow "[INSTALL] Curl"
  sudo apt-get install -y curl
  p_green "[INSTALL] Curl: DONE\!"

  read -p "Do you wanna continue? [y/n] " cont
  if [ "$cont" = "n" ]; then
    return 1;
  fi

  p_yellow "[INSTALL] Git"
  sudo apt-get install -y git
  sudo apt-get install -y git-core bash-completion
  p_green "[INSTALL] Git: DONE\!"

  read -p "Do you wanna continue? [y/n] " cont
  if [ "$cont" = "n" ]; then
    return 1;
  fi

  p_yellow "[INSTALL] NVM"
  sudo curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  p_green "[INSTALL] NVM: DONE\!"

  read -p "Do you wanna continue? [y/n] " cont
  if [ "$cont" = "n" ]; then
    return 1;
  fi

  p_yellow "[INSTALL] NodeJS"
  # sudo curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  # sudo apt-get install -y nodejs
  nvm install 0.10
  nvm alias old 0.10
  nvm install stable
  nvm alias default stable
  nvm use default
  p_green "[INSTALL] NodeJS: Using ${$(nvm current)//v}\!"

  read -p "Do you wanna continue? [y/n] " cont
  if [ "$cont" = "n" ]; then
    return 1;
  fi
  p_green "[INSTALL] NodeJS: DONE\!"

  read -p "Do you wanna continue? [y/n] " cont
  if [ "$cont" = "n" ]; then
    return 1;
  fi

  p_yellow "[INSTALL] Yarn"
  sudo npm install -g yarn
  p_green "[INSTALL] Yarn: DONE\!"

  read -p "Do you wanna continue? [y/n] " cont
  if [ "$cont" = "n" ]; then
    return 1;
  fi

  p_yellow "[INSTALL] MongoDB"
  sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
  echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
  sudo apt-get update
  sudo apt-get install -y mongodb-org
  sudo chmod -R 777 /etc/systemd/system/
  sudo echo "[Unit]" >> /etc/systemd/system/mongodb.service
  sudo echo "Description=High-performance, schema-free document-oriented database" >> /etc/systemd/system/mongodb.service
  sudo echo "After=network.target" >> /etc/systemd/system/mongodb.service
  sudo echo "" >> /etc/systemd/system/mongodb.service
  sudo echo "[Service]" >> /etc/systemd/system/mongodb.service
  sudo echo "User=mongodb" >> /etc/systemd/system/mongodb.service
  sudo echo "ExecStart=/usr/bin/mongod --quiet --config /etc/mongod.conf" >> /etc/systemd/system/mongodb.service
  sudo echo "" >> /etc/systemd/system/mongodb.service
  sudo echo "[Install]" >> /etc/systemd/system/mongodb.service
  sudo echo "WantedBy=multi-user.target" >> /etc/systemd/system/mongodb.service
  sudo systemctl start mongodb
  sudo systemctl enable mongodb
  p_green "[INSTALL] MongoDB: DONE\!"

  read -p "Do you wanna continue? [y/n] " cont
  if [ "$cont" = "n" ]; then
    return 1;
  fi

  p_yellow "[INSTALL] Mongo-Hacker"
  sudo git clone https://github.com/TylerBrock/mongo-hacker.git /mongo-hacker
  sudo make -C /mongo-hacker
  sudo make install -C /mongo-hacker
  p_green "[INSTALL] Mongo-Hacker: DONE\!"

  read -p "Do you wanna continue? [y/n] " cont
  if [ "$cont" = "n" ]; then
    return 1;
  fi

  p_yellow "[INSTALL] PostgreSQL"
  sudo apt-get install -y postgresql postgresql-contrib
  p_green "[INSTALL] PostgreSQL: DONE\!"

  read -p "Do you wanna continue? [y/n] " cont
  if [ "$cont" = "n" ]; then
    return 1;
  fi

  p_yellow "[INSTALL] NGINX"
  sudo apt-get install -y nginx
  sudo ufw allow 'Nginx HTTP'
  sudo systemctl start nginx
  sudo systemctl enable nginx
  p_green "[INSTALL] NGINX: DONE\!"

  read -p "Do you wanna continue? [y/n] " cont
  if [ "$cont" = "n" ]; then
    return 1;
  fi

  p_yellow "[INSTALL] REDIS"
  sudo apt-get install -y build-essential tcl
  sudo curl -fsSL -o /tmp/redis-stable.tar.gz http://download.redis.io/redis-stable.tar.gz
  sudo tar xzvf /tmp/redis-stable.tar.gz -C /tmp/
  sudo make -C /tmp/redis-stable
  sudo make test -C /tmp/redis-stable
  sudo make install -C /tmp/redis-stable
  sudo mkdir /etc/redis
  sudo cp /tmp/redis-stable/redis.conf /etc/redis
  sudo sed -i 's/^supervised no/supervised systemd/g' /etc/redis/redis.conf
  sudo sed -i 's/^supervised upstart/supervised systemd/g' /etc/redis/redis.conf
  sudo sed -i 's/^supervised auto/supervised systemd/g' /etc/redis/redis.conf
  N=$(sudo awk '/^dir/{print NR}' /etc/redis/redis.conf)
  sudo sed -i '/^dir/a dir \/var\/lib\/redis/g' /etc/redis/redis.conf
  sudo sed -i "${N}d" /etc/redis/redis.conf
  sudo echo "[Unit]" >> /etc/systemd/system/redis.service
  sudo echo "Description=Redis In-Memory Data Store" >> /etc/systemd/system/redis.service
  sudo echo "After=network.target" >> /etc/systemd/system/redis.service
  sudo echo "" >> /etc/systemd/system/redis.service
  sudo echo "[Service]" >> /etc/systemd/system/redis.service
  sudo echo "User=redis" >> /etc/systemd/system/redis.service
  sudo echo "Group=redis" >> /etc/systemd/system/redis.service
  sudo echo "ExecStart=/usr/local/bin/redis-server /etc/redis/redis.conf" >> /etc/systemd/system/redis.service
  sudo echo "ExecStop=/usr/local/bin/redis-cli shutdown" >> /etc/systemd/system/redis.service
  sudo echo "Restart=always" >> /etc/systemd/system/redis.service
  sudo echo "" >> /etc/systemd/system/redis.service
  sudo echo "[Install]" >> /etc/systemd/system/redis.service
  sudo echo "WantedBy=multi-user.target" >> /etc/systemd/system/redis.service
  sudo adduser --system --group --no-create-home redis
  sudo mkdir /var/lib/redis
  sudo chown redis:redis /var/lib/redis
  sudo chmod 770 /var/lib/redis
  sudo systemctl start redis
  sudo systemctl enable redis
  p_green "[INSTALL] REDIS: DONE\!"

  read -p "Do you wanna continue? [y/n] " cont
  if [ "$cont" = "n" ]; then
    return 1;
  fi

  p_yellow "[INSTALL] MySQL"
  sudo apt-get install mysql-server
  p_green "[INSTALL] MySQL: DONE\!"

  read -p "Do you wanna continue? [y/n] " cont
  if [ "$cont" = "n" ]; then
    return 1;
  fi

  p_yellow "[INSTALL] PHP"
  sudo apt-get install -y php-fpm php-mysql
  p_green "[INSTALL] PHP: DONE\!"

  read -p "Do you wanna continue? [y/n] " cont
  if [ "$cont" = "n" ]; then
    return 1;
  fi

  # p_yellow "[INSTALL] Sublime Text 3"
  # sudo add-apt-repository ppa:webupd8team/sublime-text-3
  # sudo apt-get update
  # sudo apt-get install -y sublime-text-installer
  # subl
  # p_green "[INSTALL] Sublime Text 3: DONE\!"

  # read -p "Do you wanna continue? [y/n] " cont
  # if [ "$cont" = "n" ]; then
  #   return 1;
  # fi

  p_yellow "[INSTALL] VS Code"
  curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
  sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
  sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
  sudo apt-get update
  sudo apt-get install code
  p_green "[INSTALL] VS Code: DONE\!"

  read -p "Do you wanna continue? [y/n] " cont
  if [ "$cont" = "n" ]; then
    return 1;
  fi

  p_yellow "[INSTALL] Google Chrome"
  sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  sudo apt-get -y update
  sudo apt-get install -y google-chrome-stable
  p_green "[INSTALL] Google Chrome: DONE\!"

  read -p "Do you wanna continue? [y/n] " cont
  if [ "$cont" = "n" ]; then
    return 1;
  fi

  p_yellow "[INSTALL] Unzip"
  sudo apt-get install unzip
  p_green "[INSTALL] Unzip: DONE\!"

  read -p "Do you wanna continue? [y/n] " cont
  if [ "$cont" = "n" ]; then
    return 1;
  fi

  p_yellow "[INSTALL] Terminator"
  sudo add-apt-repository ppa:gnome-terminator
  sudo apt-get -y update
  sudo apt-get install -y terminator
  p_green "[INSTALL] Terminator: DONE\!"

  read -p "Do you wanna continue? [y/n] " cont
  if [ "$cont" = "n" ]; then
    return 1;
  fi

  p_yellow "[INSTALL] Httpie"
  sudo apt-get install -y httpie
  p_green "[INSTALL] Httpie: DONE\!"

  read -p "Do you wanna continue? [y/n] " cont
  if [ "$cont" = "n" ]; then
    return 1;
  fi

  p_yellow "[INSTALL] Postman"
  sudo curl -fsSL -o /tmp/postman.tar.gz 'https://dl.pstmn.io/download/latest/linux64'
  sudo tar -xzf /tmp/postman.tar.gz -C /opt
  sudo ln -s /opt/Postman/Postman /usr/bin/postman
  p_green "[INSTALL] Postman: DONE\!"

  read -p "Do you wanna continue? [y/n] " cont
  if [ "$cont" = "n" ]; then
    return 1;
  fi

  p_yellow "[INSTALL] Dropbox"
  cd ~ && wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -
  ~/.dropbox-dist/dropboxd
  p_green "[INSTALL] Dropbox: DONE\!"

  read -p "Do you wanna continue? [y/n] " cont
  if [ "$cont" = "n" ]; then
    return 1;
  fi

  p_yellow "[INSTALL] Fonts"
  p_yellow "> Hack"
  i_fonts "Hack" "https://github.com/chrissimpkins/Hack/releases/download/v2.013/Hack-v2_013-ttf.zip"
  p_green "> Hack DONE\!"
  p_yellow "> Source Code Pro"
  i_fonts "SourceCodePro" "https://github.com/adobe-fonts/source-code-pro/archive/2.010R-ro/1.030R-it.zip"
  p_green "> Source Code Pro DONE\!"
  p_green "[INSTALL] Fonts: DONE\!"

  read -p "Do you wanna continue? [y/n] " cont
  if [ "$cont" = "n" ]; then
    return 1;
  fi

  p_yellow "[INSTALL] ZSH"
  sudo apt-get install -y zsh
  p_green "[INSTALL] ZSH: DONE\!"

  read -p "Do you wanna continue? [y/n] " cont
  if [ "$cont" = "n" ]; then
    return 1;
  fi

  p_yellow "[INSTALL] Oh-my-zsh"
  cd
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  p_green "[INSTALL] Oh-my-zsh: DONE\!"

  p_green "\o/ Finish... \o/"
}

install
