#!/bin/bash

# Inspired by https://github.com/thiagommedeiros/dotfiles

GREEN='\033[0;32m'
RED="\033[0;31m"
NC="\033[0m"

function p_red() {
  printf "\n${RED}$1${NC}\n"
}

function p_green() {
  printf "\n${GREEN}$1${NC}\n"
}

function update() {
  p_red "[UPDATE] Oh-my-zsh"
  TEST_CURRENT_SHELL=$(expr "$SHELL" : '.*/\(.*\)')
  if [ "$TEST_CURRENT_SHELL" != "zsh" ]; then
    if hash chsh >/dev/null 2>&1; then
      chsh -s $(grep /zsh$ /etc/shells | tail -1)
    fi
  fi
  sed -i "s/USER/${USER}/" zsh/.zshrc
  cp zsh/.zshrc ~/
  cp zsh/materialshell-oceanic.zsh-theme ~/.oh-my-zsh/themes
  p_green "[UPDATE] Oh-my-zsh: DONE\!"

  p_red "[UPDATE] Terminator"
  cp terminator/config ~/.config/terminator/config
  p_green "[UPDATE] Terminator: DONE\!"

  p_red "[UPDATE] Git"
  cp git/.gitconfig ~/
  p_green "[UPDATE] Git: DONE\!"

  p_red "[UPDATE] Sublime Text 3"
  cp st3/Package\ Control.sublime-settings ~/.config/sublime-text-3/Packages/User/Package\ Control.sublime-settings
  cp st3/Base\ File.sublime-settings ~/.config/sublime-text-3/Packages/User/Base\ File.sublime-settings
  cp st3/Preferences.sublime-settings ~/.config/sublime-text-3/Packages/User/Preferences.sublime-settings
  cp st3/Emmet.sublime-settings ~/.config/sublime-text-3/Packages/User/Emmet.sublime-settings
  mv st3/Material\ Theme.sublime-package ~/.config/sublime-text-3/Installed\ Packages/
  p_green "[UPDATE] Sublime Text 3: DONE\!"
}

read -p "You are logged as ${USER}, do you wanna continue? [y/n] " cont
if [ "$cont" = "y" ]; then
  update
fi
